### ISSUE TITLE
Support for MongoDB URI

### ISSUE THREAD

**Issue by etteru** [emirotin/mongodb-migrations#32]
Would it be possible to support MongoDB Connection URIs (see https://docs.mongodb.com/v3.2/reference/connection-string/)? I would like to specify my database connection with a string of the form "mongodb://localhost:27017/test".

This used to work in the past (using the "url" config parameter), but it doesn't seem to work anymore with version 0.7.0 due to the stronger validation of the config option ("host" is required when "replicaset" is not set).

Many thanks!

**Comment by emirotin** [comment]
You're totally right, I forgot to check for this param! Will publish a patch version fixing this today.
Thanks for reporting.

**Comment by emirotin** [comment]
Hey @etteru I had some important fixes pending so instead of a patch version I've released 0.8.0. 0.7.0 is now deprecated.

Please check the changelog, the changes in 0.8.0 are _formally_ breaking, but they are healthy and required, and shouldn't affect 99% of the users - unless you've relied on the previous behavior.

**Comment by etteru** [comment]
Hey @emirotin, thanks a lot for the quick fix! I'll try out the new version on Monday.

P.S. Maybe you could also update the readme (with respect to the "url" parameter).

**Comment by emirotin** [comment]
Ah, that's why I've missed it — it's not in the docs. Good catch, will fix.
