### ISSUE TITLE
Duplicate migration history

### ISSUE THREAD

**Issue by alyyousuf7** [emirotin/mongodb-migrations#34]
After I updated the module from 0.6.1 to 0.8.1, and ran the migration, it said all the migration already ran before, but it still added more entries to the migration history table.
I repeated it, and it still made more entries.

**Comment by emirotin** [comment]
Interesting, looks like regression. Thanks for reporting, I will investigate and fix.
I thin kI know the reason. I made it add the records for the void migrations (missing the up / down methods correspondingly) to mark them as being processed. Likely the same code acts on the migrations that are skipped because of them being already ran.
The

**Comment by emirotin** [comment]
Oh, actually it _can_ be harmful when running migrations down - it will cause them to be ran down twice because of `deleteOne` used to remove the recorded ID.

**Comment by emirotin** [comment]
The fix is merged and published as 0.8.2. 
Please let me know if you don't observe the issue anymore with consequent runs.
A separate dedupe command will be released later.

**Comment by emirotin** [comment]
The new `mm dedupe` command is introduced in 0.8.3, please give it a try. It should keep exactly one copy of each migration record in the DB.
